# Generated by Django 5.2.7 on 2025-10-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
